apiVersion: v1
kind: PersistentVolume
metadata:
  name: flexisip-linphone-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.119
    path: /mnt/k3s/linphone
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flexisip-linphone-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: flexisip-linphone-pv
  storageClassName: manual