apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sip-cert
  namespace: default
spec:
  secretName: sip-tls-cert
  dnsNames:
    - sip.ficusonline.com
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
