apiVersion: v1
kind: PersistentVolume
metadata:
  name: phpmyadmin-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    server: 192.168.1.119
    path: /mnt/k3s/phpmyadmin

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpmyadmin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 500Mi
  storageClassName: manual
  volumeName: phpmyadmin-pv
