apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  selector:
    app: mariadb
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-headless
spec:
  clusterIP: None
  selector:
    app: mariadb
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
