apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
#  type: NodePort
  selector:
    app: apache
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  ports:
  - name: http
    port: 80
    targetPort: 8080
#    nodePort: 30080
#  - name: https
#    port: 8443
#    targetPort: 8443
#    nodePort: 30443
